// Generated by scripts/generate.py. Do not edit.
import * as M from "./models.js";
import { Transport, type RequestOptions, type Upload, type EventFrame } from "./transport.js";
export class Robotomail extends Transport {
  /** Create an account */
  createSignup(body: M.SignupRequest, options: RequestOptions = {}): Promise<M.SignupResponse> { return this.request<M.SignupResponse>("POST", `/signup`, body, undefined, options); }
  /** Check if an account slug is available */
  checkSlugAvailability(params: M.CheckSlugAvailabilityParams, options: RequestOptions = {}): Promise<M.SlugAvailability> { return this.request<M.SlugAvailability>("GET", `/signup/check-slug`, undefined, params, options); }
  /** Get account stats */
  getAccount(options: RequestOptions = {}): Promise<M.AccountResponse> { return this.request<M.AccountResponse>("GET", `/account`, undefined, undefined, options); }
  /** Delete account permanently */
  deleteAccount(body: M.DeleteAccountRequest, options: RequestOptions = {}): Promise<M.DeletedResponse> { return this.request<M.DeletedResponse>("DELETE", `/account`, body, undefined, options); }
  /** Send the welcome email */
  sendWelcomeEmail(options: RequestOptions = {}): Promise<M.OkResponse> { return this.request<M.OkResponse>("POST", `/account/welcome`, undefined, undefined, options); }
  /** Resolve post-verification target */
  setPostVerifyTarget(options: RequestOptions = {}): Promise<M.SetPostVerifyTargetResponse> { return this.request<M.SetPostVerifyTargetResponse>("POST", `/account/post-verify-target`, undefined, undefined, options); }
  /** List API keys */
  listApiKeys(options: RequestOptions = {}): Promise<M.ApiKeyListResponse> { return this.request<M.ApiKeyListResponse>("GET", `/api-keys`, undefined, undefined, options); }
  /** Create an API key */
  createApiKey(body: M.CreateApiKeyRequest, options: RequestOptions = {}): Promise<M.CreateApiKeyResponse> { return this.request<M.CreateApiKeyResponse>("POST", `/api-keys`, body, undefined, options); }
  /** Revoke an API key */
  revokeApiKey(id: string, options: RequestOptions = {}): Promise<M.RevokedResponse> { return this.request<M.RevokedResponse>("DELETE", `/api-keys/${this.segment(id)}`, undefined, undefined, options); }
  /** List mailboxes */
  listMailboxes(options: RequestOptions = {}): Promise<M.MailboxListResponse> { return this.request<M.MailboxListResponse>("GET", `/mailboxes`, undefined, undefined, options); }
  /** Create a mailbox */
  createMailbox(body: M.CreateMailboxRequest, options: RequestOptions = {}): Promise<M.MailboxResponse> { return this.request<M.MailboxResponse>("POST", `/mailboxes`, body, undefined, options); }
  /** Get a mailbox */
  getMailbox(id: string, options: RequestOptions = {}): Promise<M.MailboxResponse> { return this.request<M.MailboxResponse>("GET", `/mailboxes/${this.segment(id)}`, undefined, undefined, options); }
  /** Update a mailbox */
  updateMailbox(id: string, body: M.UpdateMailboxRequest, options: RequestOptions = {}): Promise<M.MailboxResponse> { return this.request<M.MailboxResponse>("PATCH", `/mailboxes/${this.segment(id)}`, body, undefined, options); }
  /** Delete a mailbox */
  deleteMailbox(id: string, options: RequestOptions = {}): Promise<M.DeletedResponse> { return this.request<M.DeletedResponse>("DELETE", `/mailboxes/${this.segment(id)}`, undefined, undefined, options); }
  /** List messages in a mailbox */
  listMessages(id: string, params: M.ListMessagesParams = {}, options: RequestOptions = {}): Promise<M.MessageListResponse> { return this.request<M.MessageListResponse>("GET", `/mailboxes/${this.segment(id)}/messages`, undefined, params, options); }
  /** Send an email from a mailbox */
  sendMessage(id: string, body: M.SendMessageRequest, options: RequestOptions = {}): Promise<M.MessageResponse> { return this.request<M.MessageResponse>("POST", `/mailboxes/${this.segment(id)}/messages`, body, undefined, options); }
  /** Get a message */
  getMessage(id: string, msgId: string, options: RequestOptions = {}): Promise<M.MessageResponse> { return this.request<M.MessageResponse>("GET", `/mailboxes/${this.segment(id)}/messages/${this.segment(msgId)}`, undefined, undefined, options); }
  /** List threads in a mailbox */
  listThreads(id: string, options: RequestOptions = {}): Promise<M.ThreadListResponse> { return this.request<M.ThreadListResponse>("GET", `/mailboxes/${this.segment(id)}/threads`, undefined, undefined, options); }
  /** Get a thread with its messages */
  getThread(id: string, tid: string, options: RequestOptions = {}): Promise<M.ThreadResponse> { return this.request<M.ThreadResponse>("GET", `/mailboxes/${this.segment(id)}/threads/${this.segment(tid)}`, undefined, undefined, options); }
  /** Upload an attachment */
  uploadAttachment(file: Upload, options: RequestOptions = {}): Promise<M.AttachmentUploadResponse> { return this.request<M.AttachmentUploadResponse>("POST", `/attachments`, undefined, undefined, options, file); }
  /** Get an attachment download URL */
  downloadAttachment(id: string, options: RequestOptions = {}): Promise<M.AttachmentDownload> { return this.request<M.AttachmentDownload>("GET", `/attachments/${this.segment(id)}`, undefined, undefined, options); }
  /** Delete an attachment */
  deleteAttachment(id: string, options: RequestOptions = {}): Promise<M.DeletedResponse> { return this.request<M.DeletedResponse>("DELETE", `/attachments/${this.segment(id)}`, undefined, undefined, options); }
  /** List custom domains */
  listDomains(options: RequestOptions = {}): Promise<M.DomainListResponse> { return this.request<M.DomainListResponse>("GET", `/domains`, undefined, undefined, options); }
  /** Add a custom domain */
  createDomain(body: M.CreateDomainRequest, options: RequestOptions = {}): Promise<M.DomainCreatedResponse> { return this.request<M.DomainCreatedResponse>("POST", `/domains`, body, undefined, options); }
  /** Get a domain and its DNS records */
  getDomain(id: string, options: RequestOptions = {}): Promise<M.DomainResponse> { return this.request<M.DomainResponse>("GET", `/domains/${this.segment(id)}`, undefined, undefined, options); }
  /** Delete a domain */
  deleteDomain(id: string, options: RequestOptions = {}): Promise<M.DeletedResponse> { return this.request<M.DeletedResponse>("DELETE", `/domains/${this.segment(id)}`, undefined, undefined, options); }
  /** Trigger domain verification */
  verifyDomain(id: string, options: RequestOptions = {}): Promise<M.DomainVerificationResponse> { return this.request<M.DomainVerificationResponse>("POST", `/domains/${this.segment(id)}/verify`, undefined, undefined, options); }
  /** List webhooks */
  listWebhooks(options: RequestOptions = {}): Promise<M.WebhookListResponse> { return this.request<M.WebhookListResponse>("GET", `/webhooks`, undefined, undefined, options); }
  /** Create a webhook */
  createWebhook(body: M.CreateWebhookRequest, options: RequestOptions = {}): Promise<M.WebhookCreatedResponse> { return this.request<M.WebhookCreatedResponse>("POST", `/webhooks`, body, undefined, options); }
  /** Get a webhook */
  getWebhook(id: string, options: RequestOptions = {}): Promise<M.WebhookResponse> { return this.request<M.WebhookResponse>("GET", `/webhooks/${this.segment(id)}`, undefined, undefined, options); }
  /** Update a webhook */
  updateWebhook(id: string, body: M.UpdateWebhookRequest, options: RequestOptions = {}): Promise<M.WebhookResponse> { return this.request<M.WebhookResponse>("PATCH", `/webhooks/${this.segment(id)}`, body, undefined, options); }
  /** Delete a webhook */
  deleteWebhook(id: string, options: RequestOptions = {}): Promise<M.DeletedResponse> { return this.request<M.DeletedResponse>("DELETE", `/webhooks/${this.segment(id)}`, undefined, undefined, options); }
  /** List webhook deliveries */
  listWebhookDeliveries(id: string, options: RequestOptions = {}): Promise<M.WebhookDeliveryListResponse> { return this.request<M.WebhookDeliveryListResponse>("GET", `/webhooks/${this.segment(id)}/deliveries`, undefined, undefined, options); }
  /** Stream inbox events over SSE */
  streamEvents(params: M.StreamEventsParams = {}, options: RequestOptions = {}): AsyncGenerator<EventFrame> { return this.stream(params, options); }
  /** List suppressed addresses */
  listSuppressions(options: RequestOptions = {}): Promise<M.SuppressionListResponse> { return this.request<M.SuppressionListResponse>("GET", `/suppressions`, undefined, undefined, options); }
  /** Suppress an address */
  createSuppression(body: M.CreateSuppressionRequest, options: RequestOptions = {}): Promise<M.SuppressionResponse> { return this.request<M.SuppressionResponse>("POST", `/suppressions`, body, undefined, options); }
  /** Remove a suppression entry */
  deleteSuppression(id: string, options: RequestOptions = {}): Promise<M.DeletedResponse> { return this.request<M.DeletedResponse>("DELETE", `/suppressions/${this.segment(id)}`, undefined, undefined, options); }
  /** Start a plan upgrade */
  createUpgradeCheckout(body: M.UpgradeRequest, options: RequestOptions = {}): Promise<M.UpgradeCheckoutResponse> { return this.request<M.UpgradeCheckoutResponse>("POST", `/billing/upgrade`, body, undefined, options); }
  /** Resend the email verification link */
  resendVerificationEmail(body: M.ResendVerificationEmailRequest, options: RequestOptions = {}): Promise<M.OkResponse> { return this.request<M.OkResponse>("POST", `/auth/resend-verification`, body, undefined, options); }
  /** Contact support */
  submitSupportTicket(body: M.SupportRequest, options: RequestOptions = {}): Promise<M.OkResponse> { return this.request<M.OkResponse>("POST", `/support`, body, undefined, options); }
}
