// Generated by scripts/generate.py. Do not edit.
export interface ErrorBody {
  "error": string;
}

export interface EndpointNotFound {
  "error": string;
  "code": string;
  "message": string;
  "resolution": EndpointNotFoundResolution;
}

export interface UpgradeHint {
  "browserUrl": string;
  "apiEndpoint": UpgradeHintApiEndpoint;
  "hint": string;
}

export interface PaymentRequired {
  "error": string;
  "payment_required": boolean;
  "code": string;
  "upgrade": UpgradeHint;
}

export interface TrialPaymentRequired {
  "error": string;
  "payment_required": boolean;
  "code": "TRIAL_RECIPIENT_LOCKED" | "TRIAL_SEND_LIMIT" | "TRIAL_EXPIRED";
  "upgrade": UpgradeHint;
  "resetsAt"?: string;
}

export interface InboundLimitExceeded {
  "error": string;
  "code": "INBOUND_LIMIT_EXCEEDED" | "INBOUND_TRIAL_LIMIT_EXCEEDED";
  "resource": InboundLimitExceededResource;
  "upgrade": UpgradeHint;
  "recovery": "reset" | "upgrade";
  "resetAt"?: string;
}

export interface PlanLimit {
  "error": string;
  "upgrade": string;
}

export interface Suspended {
  "error": string;
  "suspended": boolean;
  "reason": string;
}

export interface DeletedResponse {
  "deleted": boolean;
}

export interface RevokedResponse {
  "revoked": boolean;
}

export interface SignupRequest {
  "email": string;
  "password": string;
  "slug": string;
  "name"?: string;
  "plan"?: string;
  "period"?: string;
  "turnstileToken"?: string;
}

export interface SignupResponse {
  "user": SignupResponseUser;
  "api_key": SignupResponseApiKey;
  "mailbox": SignupResponseMailbox;
  "mailbox_limit": number;
  "daily_send_limit": number;
  "monthly_send_limit": number;
  "email_verified": boolean;
  "next_steps": SignupResponseNextSteps;
}

export interface SandboxTrial {
  "isTrialUser": boolean;
  "active": boolean;
  "expired": boolean;
  "exhausted": boolean;
  "sendsUsed": number;
  "sendsRemaining": number;
  "sendCap": number;
  "receivesUsed": number;
  "receivesRemaining": number;
  "receiveCap": number;
  "expiresAt": string | null;
  "startedAt": string | null;
  "resetsAt"?: string | null;
}

export interface Account {
  "id": string;
  "email": string;
  "emailVerified": boolean;
  "slug": string;
  "plan": string;
  "billingPeriod": string;
  "suspended": boolean;
  "suspendedReason": string | null;
  "suspendedAt": string | null;
  "storageUsedBytes": number;
  "storageLimitBytes": number;
  "mailboxCount": number;
  "activeMailboxCount": number;
  "sentToday": number;
  "sentThisMonth": number;
  "receivedToday": number;
  "bouncedToday": number;
  "monthlyInboundCount": number;
  "monthlyInboundLimit": number;
  "monthlyInboundPercentage": number;
  "monthlyInboundResetAt": string;
  "overLimitMessageCount": number;
  "billingLinked": boolean;
  "annualAvailability": AccountAnnualAvailability;
  "trial": SandboxTrial | null;
}

export interface AccountResponse {
  "account": Account;
}

export interface ApiKeySummary {
  "id": string;
  "name": string | null;
  "prefix": string | null;
  "createdAt": string;
  "enabled": boolean;
}

export interface ApiKeyListResponse {
  "keys": Array<ApiKeySummary>;
}

export interface CreateApiKeyRequest {
  "name"?: string;
  "mailboxIds"?: Array<string>;
}

export interface CreateApiKeyResponse {
  "key": string;
  "prefix": string;
  "scoped": boolean;
}

export interface Mailbox {
  "id": string;
  "userId": string;
  "domainId": string | null;
  "address": string;
  "fullAddress": string;
  "displayName": string | null;
  "dailySendCount": number;
  "dailySendLimit": number;
  "monthlySendCount": number;
  "monthlySendLimit": number;
  "status": "ACTIVE" | "PAUSED" | "SUSPENDED";
  "pausedByBilling": boolean;
  "stalwartProvisioned": boolean;
  "suspendedAt": string | null;
  "suspendedReason": string | null;
  "suspensionIncidentId": string | null;
  "createdAt": string;
  "updatedAt": string;
  "receivedThisMonth"?: number;
}

export interface MailboxResponse {
  "mailbox": Mailbox;
}

export interface MailboxListResponse {
  "mailboxes": Array<Mailbox>;
}

export interface CreateMailboxRequest {
  "address": string;
  "domainId"?: string;
  "displayName"?: string;
}

export interface UpdateMailboxRequest {
  "displayName"?: string;
  "status"?: "ACTIVE" | "PAUSED";
}

export interface SendMessageRequest {
  "to": Array<string>;
  "cc"?: Array<string>;
  "bcc"?: Array<string>;
  "subject": string;
  "bodyText": string;
  "bodyHtml"?: string;
  "inReplyTo"?: string;
  "attachments"?: Array<string>;
  "headers"?: Record<string, string>;
}

export interface Message {
  "id": string;
  "mailboxId": string;
  "direction": "INBOUND" | "OUTBOUND";
  "messageId": string;
  "inReplyTo": string | null;
  "threadId": string | null;
  "fromAddress": string;
  "toAddresses": Array<string>;
  "ccAddresses": Array<string>;
  "bccAddresses": Array<string>;
  "subject": string;
  "bodyText": string;
  "bodyHtml": string | null;
  "headers": Record<string, unknown>;
  "status": "QUEUED" | "SENT" | "DELIVERED" | "BOUNCED" | "COMPLAINED" | "FAILED" | "RECEIVED";
  "externalMessageId": string | null;
  "hasAttachments": boolean;
  "attachmentsDropped": boolean;
  "attachmentsDroppedReason": string | null;
  "eventDispatchedAt": string | null;
  "overLimit": boolean;
  "overLimitReason": "MONTHLY" | "TRIAL" | null;
  "pendingSseEventData": unknown;
  "createdAt": string;
  "attachments"?: Array<Attachment>;
}

export interface MessageResponse {
  "message": Message;
}

export interface InboundUsage {
  "current": number;
  "limit": number;
  "percentage": number;
  "reset_date": string;
  "status": "healthy" | "approaching" | "near" | "limit_reached";
}

export interface ListMetadata {
  "overLimitCount": number;
  "upgrade": UpgradeHint;
  "limitHint"?: InboundUsage;
}

export interface MessageListResponse {
  "messages": Array<Message>;
  "metadata": ListMetadata;
}

export interface Attachment {
  "id": string;
  "messageId": string | null;
  "userId": string;
  "filename": string;
  "contentType": string;
  "sizeBytes": number;
  "r2Key": string;
  "contentId": string | null;
  "createdAt": string;
}

export interface AttachmentUploadResponse {
  "id": string;
  "filename": string;
  "sizeBytes": number;
}

export interface AttachmentDownload {
  "id": string;
  "messageId": string | null;
  "userId": string;
  "filename": string;
  "contentType": string;
  "sizeBytes": number;
  "r2Key": string;
  "contentId": string | null;
  "createdAt": string;
  "url": string;
}

export interface Thread {
  "id": string;
  "mailboxId": string;
  "subject": string;
  "messageCount": number;
  "lastMessageAt": string;
  "participants": Array<string>;
  "createdAt": string;
}

export interface ThreadDetail {
  "id": string;
  "mailboxId": string;
  "subject": string;
  "messageCount": number;
  "lastMessageAt": string;
  "participants": Array<string>;
  "createdAt": string;
  "messages": Array<Message>;
}

export interface ThreadListResponse {
  "threads": Array<Thread>;
  "metadata": ListMetadata;
}

export interface ThreadResponse {
  "thread": ThreadDetail;
}

export interface Domain {
  "id": string;
  "userId": string;
  "domain": string;
  "status": "PENDING_VERIFICATION" | "DNS_VERIFIED" | "VERIFIED" | "FAILED";
  "mxVerified": boolean;
  "spfVerified": boolean;
  "dkimVerified": boolean;
  "dmarcVerified": boolean;
  "dkimPublicKey": string | null;
  "dkimSelector": string | null;
  "externalDomainId": string | null;
  "stalwartProvisioned": boolean;
  "createdAt": string;
  "updatedAt": string;
}

export interface MxDnsRecord {
  "type": string;
  "host": string;
  "value": string;
  "priority": number;
}

export interface TxtDnsRecord {
  "type": string;
  "host": string;
  "value": string;
}

export interface DkimDnsRecord {
  "type": "CNAME" | "TXT";
  "host": string;
  "value": string;
}

export interface DnsRecords {
  "mx": MxDnsRecord;
  "sendMx": MxDnsRecord;
  "spf": TxtDnsRecord;
  "dkim": Array<DkimDnsRecord>;
  "dmarc": TxtDnsRecord;
}

export interface CreateDomainRequest {
  "domain": string;
}

export interface DomainListResponse {
  "domains": Array<Domain>;
}

export interface DomainCreatedResponse {
  "domain": Domain;
  "dnsRecords": DnsRecords;
}

export interface DomainResponse {
  "domain": Domain;
  "dnsRecords": DnsRecords | null;
}

export interface DomainVerificationResponse {
  "domain": Domain;
  "verification": DomainVerificationResponseVerification;
}

export interface Webhook {
  "id": string;
  "userId": string;
  "mailboxId": string | null;
  "url": string;
  "events": Array<"message.received" | "message.sent" | "message.delivered" | "message.bounced" | "message.complaint">;
  "headers": Record<string, string> | null;
  "status": "ACTIVE" | "PAUSED" | "FAILED";
  "failureCount": number;
  "lastTriggeredAt": string | null;
  "createdAt": string;
  "updatedAt": string;
}

export interface WebhookCreated {
  "id": string;
  "userId": string;
  "mailboxId": string | null;
  "url": string;
  "events": Array<"message.received" | "message.sent" | "message.delivered" | "message.bounced" | "message.complaint">;
  "headers": Record<string, string> | null;
  "status": "ACTIVE" | "PAUSED" | "FAILED";
  "failureCount": number;
  "lastTriggeredAt": string | null;
  "createdAt": string;
  "updatedAt": string;
  "secret": string;
}

export type WebhookHeaders = Record<string, string>;
export interface CreateWebhookRequest {
  "url": string;
  "mailboxId"?: string;
  "events": Array<"message.received" | "message.sent" | "message.delivered" | "message.bounced" | "message.complaint">;
  "headers"?: WebhookHeaders;
}

export interface UpdateWebhookRequest {
  "url"?: string;
  "events"?: Array<"message.received" | "message.sent" | "message.delivered" | "message.bounced" | "message.complaint">;
  "status"?: "ACTIVE" | "PAUSED";
  "headers"?: WebhookHeaders | null;
}

export interface WebhookListResponse {
  "webhooks": Array<Webhook>;
}

export interface WebhookResponse {
  "webhook": Webhook;
}

export interface WebhookCreatedResponse {
  "webhook": WebhookCreated;
}

export interface WebhookDelivery {
  "id": string;
  "event": string;
  "responseStatus": number | null;
  "status": "PENDING" | "DELIVERED" | "FAILED";
  "attempts": number;
  "nextRetryAt": string | null;
  "createdAt": string;
}

export interface WebhookDeliveryListResponse {
  "deliveries": Array<WebhookDelivery>;
}

export interface SuppressionEntry {
  "id": string;
  "email": string;
  "reason": "BOUNCE" | "COMPLAINT" | "MANUAL";
  "createdAt": string;
}

export interface CreateSuppressionRequest {
  "email": string;
  "reason"?: "BOUNCE" | "COMPLAINT" | "MANUAL";
}

export interface SuppressionListResponse {
  "suppressions": Array<SuppressionEntry>;
}

export interface SuppressionResponse {
  "suppression": SuppressionEntry;
}

export interface UpgradeRequest {
  "plan"?: "developer" | "growth" | "scale";
  "period"?: "monthly" | "annual";
}

export interface UpgradeCheckoutResponse {
  "checkout_url": string;
  "expires_at": number | null;
  "message": string;
}

export interface SupportRequest {
  "category": "technical" | "billing" | "account" | "other";
  "subject": string;
  "message": string;
}

export interface OkResponse {
  "ok": boolean;
}

export interface SlugAvailability {
  "available": boolean;
  "reason"?: string;
}

export interface CheckSlugAvailabilityParams {
  "slug": string;
}

export interface DeleteAccountRequest {
  "confirm": string;
}

export interface SetPostVerifyTargetResponse {
  "target": "/dashboard?verified=true" | "/onboarding";
}

export interface ListMessagesParams {
  "direction"?: "INBOUND" | "OUTBOUND";
  "threadId"?: string;
  "since"?: string;
  "limit"?: number;
  "offset"?: number;
}

export interface StreamEventsParams {
  "mailboxId"?: string;
  "events"?: string;
  "Last-Event-ID"?: string;
}

export interface ResendVerificationEmailRequest {
  "email": string;
}

export interface EndpointNotFoundResolution {
  "openapi": string;
  "docs": string;
  "endpoints": string;
  "commonEndpoints": Array<string>;
}

export interface UpgradeHintApiEndpoint {
  "method": string;
  "path": string;
}

export interface InboundLimitExceededResource {
  "type": "message" | "attachment";
  "id": string;
}

export interface SignupResponseUser {
  "id": string;
  "email": string;
  "slug": string;
  "name": string;
  "plan": string;
  "platform_email": string;
}

export interface SignupResponseApiKey {
  "key": string;
  "prefix": string;
  "name": string;
}

export interface SignupResponseMailbox {
  "id": string;
  "address": string;
  "fullAddress": string;
  "status": "ACTIVE" | "PAUSED" | "SUSPENDED";
}

export interface SignupResponseNextSteps {
  "verify_email": string;
  "add_payment": string;
  "add_domain": string;
  "send_email": string;
}

export interface AccountAnnualAvailability {
  "developer": boolean;
  "growth": boolean;
  "scale": boolean;
}

export interface DomainVerificationResponseVerification {
  "mx": boolean;
  "spf": boolean;
  "dkim": boolean;
  "dmarc": boolean;
  "allVerified": boolean;
}
